name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy to GitHub Pages
      uses: periskop/GitHub-Pages-deploy@master
      env:
        EMAIL: am@opendata.by               # must be a verified email
        GH_TOKEN: ${{  52689dcd5d15cb78f4c7b10adb9f1b51cc7416dd }} # https://github.com/settings/tokens
        BUILD_DIR: build/                     # "_site/" by default
        CNAME: periskop.opendata.by                      # in case of custom domain
